(function(g){var window=this;var SDa=function(a,b){return g.Tb(a,b)},l6=function(a){g.dn(a,"zx",g.vb());
return a},m6=function(a,b,c){g.wa(c)||(c=[String(c)]);
g.gn(a.o,b,c)},TDa=function(a,b){var c=[];
g.Rk(b,function(a){try{var b=g.GD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.FD(b)&&c.push(a):c.push(a)},a);
return c},UDa=function(a,b){var c=TDa(a,b);
(0,g.D)(c,function(a){g.GD.prototype.remove.call(this,a)},a)},VDa=function(a){if(a.Jd){if(a.Jd.locationOverrideToken)return{locationOverrideToken:a.Jd.locationOverrideToken};
if(null!=a.Jd.latitudeE7&&null!=a.Jd.longitudeE7)return{latitudeE7:a.Jd.latitudeE7,longitudeE7:a.Jd.longitudeE7}}return null},WDa=function(a,b,c,d){var e=new g.Vm(null,void 0);
a&&g.Wm(e,a);b&&g.Xm(e,b);c&&g.Ym(e,c);d&&g.Zm(e,d);return e},XDa=function(a){g.lG[a]&&(a=g.lG[a],(0,g.D)(a,function(a){g.jG[a]&&delete g.jG[a]}),a.length=0)},YDa=function(a){var b=g.iG();
if(b)if(b.clear(a),a)XDa(a);else for(var c in g.lG)XDa(c)},n6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Pm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ZDa(this,a.capabilities||""),$Da(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},ZDa=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Ca(SDa,aEa)).forEach(function(b){a.capabilities.add(b)})},$Da=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},o6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},p6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},bEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},cEa=function(a){return new o6(a)},dEa=function(a){return g.wa(a)?(0,g.J)(a,cEa):[]},q6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},r6=function(a){return g.wa(a)?"["+(0,g.J)(a,q6).join(",")+"]":"null"},s6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},eEa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},t6=function(a,b){return g.Ia(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},u6=function(a,b){return g.Ia(a,function(a){return p6(a,b)})},fEa=function(){var a=(0,g.vH)();
a&&UDa(a,a.o.ae(!0))},v6=function(){var a=g.yH("yt-remote-connected-devices")||[];
g.db(a);return a},gEa=function(a){if(g.Na(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},hEa=function(a){g.xH("yt-remote-connected-devices",a,86400)},x6=function(){if(w6)return w6;
var a=g.yH("yt-remote-device-id");a||(a=s6(),g.xH("yt-remote-device-id",a,31536E3));for(var b=v6(),c=1,d=a;g.Ma(b,d);)c++,d=a+"#"+c;return w6=d},y6=function(){var a=v6(),b=x6();
g.Ma(a,b);g.AH()&&g.fb(a,b);a=gEa(a);if(g.Na(a))try{g.TG("remote_sid")}catch(c){}else try{g.SG("remote_sid",a.join(","),-1)}catch(c){}},iEa=function(){return g.yH("yt-remote-session-browser-channel")},jEa=function(){return g.yH("yt-remote-local-screens")||[]},kEa=function(){g.xH("yt-remote-lounge-token-expiration",!0,86400)},lEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(jEa(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Dm)(c,function(a){return!g.Ma(b,a)})&&kEa();
g.xH("yt-remote-local-screens",a,31536E3)},mEa=function(a,b){g.xH("yt-remote-session-browser-channel",a);
g.xH("yt-remote-session-screen-id",b);var c=v6(),d=x6();g.Ma(c,d)||c.push(d);hEa(c);y6()},z6=function(a){a||(g.zH("yt-remote-session-screen-id"),g.zH("yt-remote-session-video-id"));
y6();a=v6();g.Sa(a,x6());hEa(a)},nEa=function(){if(!A6){var a=g.RD();
a&&(A6=new g.AD(a))}return A6?!!A6.get("yt-remote-use-staging-server"):!1},oEa=function(){var a=window.document.createElement("a");
g.hd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},pEa=function(a,b,c){c=void 0===c?null:c;
var d=g.Od("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.jd(d,g.me("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},qEa=function(a){a=void 0===a?null:a;
var b=oEa(),c=window.document.getElementById(b),d=c&&g.sF(c,"loaded");d||c&&!d||(c=pEa(b,function(){g.sF(c,"loaded")||(g.rF(c,"loaded","true"),g.pG(b),g.rE(g.Ca(YDa,b),0))},a))},rEa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):qEa(a)},B6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},sEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},C6=function(a){a.length?tEa(a.shift(),function(){C6(a)}):D6()},uEa=function(a){return"chrome-extension://"+a+E6},tEa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},F6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},D6=function(){var a=sEa();
a&&a(!1,"No cast extension found")},G6=function(){if(vEa){var a=2,b=sEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;tEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",D6,c)}},wEa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(G6(),a({command:"cast.sender.init"}))},xEa=function(){G6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);C6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+E6,"//www.gstatic.com/eureka/clank"+E6])},H6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Bd=b;this.D=(0,g.B)(this.WK,this);this.o=!1;this.A=0;this.B=this.Ea=null;this.C=[]},I6=function(){},J6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.ln(this);this.A=new g.Bg;this.A.setInterval(250)},zEa=function(a,b,c){a.Uj=1;
a.wh=l6(b.clone());a.gj=c;a.D=!0;yEa(a,null)},K6=function(a,b,c,d,e){a.Uj=1;
a.wh=l6(b.clone());a.gj=null;a.D=c;e&&(a.iF=!1);yEa(a,d)},yEa=function(a,b){a.Ok=(0,g.H)();
L6(a);a.Wh=a.wh.clone();m6(a.Wh,"t",a.F);a.zn=0;a.Tc=a.o.Gs(a.o.pn()?b:null);0<a.xt&&(a.Cq=new g.wl((0,g.B)(a.DG,a,a.Tc),a.xt));a.Y.W(a.Tc,"readystatechange",a.oW);var c=a.Fi?g.cc(a.Fi):{};a.gj?(a.tr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Tc.send(a.Wh,a.tr,a.gj,c)):(a.tr="GET",a.iF&&!g.Jd&&(c.Connection="close"),a.Tc.send(a.Wh,a.tr,null,c));a.o.Cf(1)},CEa=function(a,b,c){for(var d=!0;!a.oi&&a.zn<c.length;){var e=AEa(a,c);
if(e==M6){4==b&&(a.xh=4,N6(15),d=!1);break}else if(e==BEa){a.xh=4;N6(16);d=!1;break}else O6(a,e)}4==b&&0==c.length&&(a.xh=1,N6(17),d=!1);a.Jf=a.Jf&&d;d||(P6(a),Q6(a))},AEa=function(a,b){var c=a.zn,d=b.indexOf("\n",c);
if(-1==d)return M6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return BEa;d+=1;if(d+c>b.length)return M6;var e=b.substr(d,c);a.zn=d+c;return e},EEa=function(a,b){a.Ok=(0,g.H)();
L6(a);var c=b?window.location.hostname:"";a.Wh=a.wh.clone();g.dn(a.Wh,"DOMAIN",c);g.dn(a.Wh,"t",a.F);try{a.Kf=new window.ActiveXObject("htmlfile")}catch(n){P6(a);a.xh=7;N6(22);Q6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in R6)k=R6[l];else if(l in DEa)k=R6[l]=DEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=R6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.Ac("b/12014412"),d+"</body></html>");a.Kf.open();a.Kf.write(g.ad(c));a.Kf.close();a.Kf.parentWindow.m=(0,g.B)(a.xV,a);a.Kf.parentWindow.d=(0,g.B)(a.tE,a,!0);a.Kf.parentWindow.rpcClose=(0,g.B)(a.tE,a,!1);c=a.Kf.createElement("DIV");a.Kf.parentWindow.document.body.appendChild(c);d=g.Oc(a.Wh.toString());d=g.ob(g.Lc(d));d=g.kd(g.Ac("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,g.ad(d));a.o.Cf(1)},
L6=function(a){a.jx=(0,g.H)()+a.C;
FEa(a,a.C)},FEa=function(a,b){if(null!=a.kl)throw Error("WatchDog timer not null");
a.kl=S6((0,g.B)(a.OV,a),b)},T6=function(a){a.kl&&(g.x.clearTimeout(a.kl),a.kl=null)},Q6=function(a){a.o.yA()||a.oi||a.o.lq(a)},P6=function(a){T6(a);
g.lf(a.Cq);a.Cq=null;a.A.stop();g.rn(a.Y);if(a.Tc){var b=a.Tc;a.Tc=null;b.abort();b.dispose()}a.Kf&&(a.Kf=null)},O6=function(a,b){try{a.o.lE(a,b),a.o.Cf(4)}catch(c){}},HEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;GEa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){HEa(a,b,c,d,f)},f)})}},GEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{U6(d),c(!0)}catch(e){}};
d.onerror=function(){try{U6(d),c(!1)}catch(e){}};
d.onabort=function(){try{U6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{U6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},U6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},IEa=function(a){this.o=a;
this.A=new I6},JEa=function(a){var b=V6(a.o,a.rl,"/mail/images/cleardot.gif");
l6(b);HEa(b.toString(),5E3,(0,g.B)(a.bK,a),3,2E3);a.Cf(1)},X6=function(a){var b=a.o.J;
if(null!=b)N6(5),b?(N6(11),W6(a.o,a,!1)):(N6(12),W6(a.o,a,!0));else if(a.Ge=new J6(a,void 0,void 0,void 0),a.Ge.Fi=a.vt,b=a.o,b=V6(b,b.pn()?a.Zl:null,a.wt),N6(5),!g.Hd||g.rc(10))m6(b,"TYPE","xmlhttp"),K6(a.Ge,b,!1,a.Zl,!1);else{m6(b,"TYPE","html");var c=a.Ge;a=!!a.Zl;c.Uj=3;c.wh=l6(b.clone());EEa(c,a)}},Y6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new I6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},KEa=function(a,b){this.o=a;
this.map=b;this.context=null},LEa=function(a){g.nf.call(this,"statevent",a)},MEa=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},NEa=function(a){g.nf.call(this,"serverreachability",a)},QEa=function(a){OEa(a);
if(3==a.o){var b=a.Xm++,c=a.Uo.clone();g.dn(c,"SID",a.B);g.dn(c,"RID",b);g.dn(c,"TYPE","terminate");Z6(a,c);b=new J6(a,a.B,b,void 0);b.Uj=2;b.wh=l6(c.clone());(new window.Image).src=b.wh;b.Ok=(0,g.H)();L6(b)}PEa(a)},REa=function(a){a.xK(1,0);
a.Uo=V6(a,null,a.qt);$6(a)},OEa=function(a){a.nh&&(a.nh.abort(),a.nh=null);
a.xc&&(a.xc.cancel(),a.xc=null);a.yg&&(g.x.clearTimeout(a.yg),a.yg=null);a7(a);a.fe&&(a.fe.cancel(),a.fe=null);a.rh&&(g.x.clearTimeout(a.rh),a.rh=null)},SEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new KEa(a.hR++,b));2!=a.o&&3!=a.o||$6(a)},$6=function(a){a.fe||a.rh||(a.rh=S6((0,g.B)(a.rE,a),0),a.Jj=0)},UEa=function(a,b){if(1==a.o){if(!b){a.Xm=Math.floor(1E5*Math.random());
var c=a.Xm++,d=new J6(a,"",c,void 0);d.Fi=null;var e=b7(a),f=a.Uo.clone();g.dn(f,"RID",c);g.dn(f,"CVER","1");Z6(a,f);zEa(d,f,e);a.fe=d;a.o=2}}else 3==a.o&&(b?TEa(a,b):0==a.A.length||a.fe||TEa(a))},TEa=function(a,b){if(b)if(6<a.ri){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Xm-1;var d=b7(a)}else c=b.G,d=b.gj;else c=a.Xm++,d=b7(a);var e=a.Uo.clone();g.dn(e,"SID",a.B);g.dn(e,"RID",c);g.dn(e,"AID",a.kk);Z6(a,e);c=new J6(a,a.B,c,a.Jj+1);c.Fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.fe=c;zEa(c,e,d)},Z6=function(a,b){if(a.Ad){var c=a.Ad.dA();
c&&g.Hb(c,function(a,c){g.dn(b,c,a)})}},b7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.ri&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.ri?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},VEa=function(a){a.xc||a.yg||(a.G=1,a.yg=S6((0,g.B)(a.qE,a),0),a.xj=0)},c7=function(a){if(a.xc||a.yg||3<=a.xj)return!1;
a.G++;a.yg=S6((0,g.B)(a.qE,a),WEa(a,a.xj));a.xj++;return!0},W6=function(a,b,c){a.rr=c;
a.Wf=b.Lg;a.F||REa(a)},a7=function(a){null!=a.si&&(g.x.clearTimeout(a.si),a.si=null)},WEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},d7=function(a,b){if(2==b||9==b){var c=null;
a.Ad&&(c=null);var d=(0,g.B)(a.eX,a);c||(c=new g.Vm("//www.google.com/images/cleardot.gif"),l6(c));GEa(c.toString(),1E4,d)}else N6(2);XEa(a,b)},XEa=function(a,b){a.o=0;
a.Ad&&a.Ad.dz(b);PEa(a);OEa(a)},PEa=function(a){a.o=0;
a.Wf=-1;if(a.Ad)if(0==a.C.length&&0==a.A.length)a.Ad.rs();else{g.Va(a.C);var b=g.Va(a.A);a.C.length=0;a.A.length=0;a.Ad.rs(b)}},V6=function(a,b,c){var d=g.en(c);
if(""!=d.A)b&&g.Xm(d,b+"."+d.A),g.Ym(d,d.D);else{var e=window.location;d=WDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Hl&&g.Hb(a.Hl,function(a,b){g.dn(d,b,a)});
g.dn(d,"VER",a.ri);Z6(a,d);return d},S6=function(a,b){if(!g.ya(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},N6=function(a){e7.dispatchEvent(new LEa(e7,a))},YEa=function(){},ZEa=function(a,b){this.action=a;
this.params=b||{}},f7=function(a,b){g.L.call(this);
this.o=new g.V(this.oV,0,this);g.M(this,this.o);this.Bd=5E3;this.A=0;if(g.ya(a))b&&(a=(0,g.B)(a,b));else if(a&&g.ya(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},g7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.zD;this.A=new f7(this.MX,this);this.o=this.ib=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},$Ea=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.rr,sessionId:a.o.B,arrayId:a.o.kk}},aFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&UEa(a.o),QEa(a.o));a.H=0},h7=function(a){return!!a.o&&3==a.o.o},bFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},i7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Qg(a)||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.A=!1))},j7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Zg(c+b,{})},k7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ca(a.C,d,!0),onError:g.Ca(a.B,e),Fd:g.Ca(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.IE(b,a)},fFa=function(){var a=cFa;
dFa();l7.push(a);eFa(l7)},m7=function(a,b){dFa();
var c=l7,d=gFa(a,String(b));g.Na(c)?hFa(d):(eFa(c),(0,g.D)(c,function(a){a(d)}))},dFa=function(){l7||(l7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ta("yt.mdx.remote.debug.handlers_",l7,void 0))},hFa=function(a){var b=(n7+1)%50;
n7=b;o7[b]=a;p7||(p7=49==b)},eFa=function(a){var b=o7;
if(b[0]){var c=n7,d=p7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
o7=Array(50);n7=-1;p7=!1}},gFa=function(a,b){var c=((0,g.H)()-iFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},q7=function(a){g.$F.call(this);
this.G=a;this.o=[]},jFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},kFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Vd)(a.o,function(a){return!!t6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=jFa(a,b[d])||c;return c},lFa=function(a,b){var c=a.o.length;
a.o=(0,g.Vd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},r7=function(a,b,c,d){g.$F.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ea=window.NaN},t7=function(a){q7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;s7(this);this.info("Initializing with "+r6(this.o))},mFa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(a){return a.id}),c=j7(a.B,"/pairing/get_lounge_token_batch");
k7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.jL,a),(0,g.B)(a.iL,a))}},s7=function(a){var b=dEa(jEa());
b=(0,g.Vd)(b,function(a){return!a.uuid});
return kFa(a,b)},u7=function(a,b){lEa((0,g.J)(a.o,bEa));
b&&kEa()},w7=function(a,b){g.$F.call(this);
this.F=b;var c=g.yH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ma(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;v7("Initialized with "+g.Hg(this.o))},nFa=function(a,b,c){var d=j7(a.D,"/pairing/get_screen_availability");
k7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},x7=function(a,b){a:if(g.Nb(b)!=g.Nb(a.o))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(v7("Updated online screens: "+g.Hg(a.o)),a.o=b,a.V("screenChange"));oFa(a)},y7=function(a){(0,window.isNaN)(a.B)||g.tE(a.B);
a.B=g.rE((0,g.B)(a.mw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},v7=function(a){m7("OnlineScreenService",a)},pFa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.oc("Requesting availability of screen w/o lounge token.")});
return b},oFa=function(a){a=g.Qb(g.Ib(a.o,function(a){return a}));
g.db(a);a.length?g.xH("yt-remote-online-screen-ids",a.join(","),60):g.zH("yt-remote-online-screen-ids")},z7=function(a){q7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};qFa(this)},sFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ae();if(k=(c?u6(k,c):null)||u6(k,b)){k.uuid=b;var l=A7(a,k);nFa(a.A,l,function(a){e(a?l:null)})}else c?rFa(a,c,(0,g.B)(function(a){var f=A7(this,new o6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));nFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},tFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},rFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.IE(j7(a.F,"/pairing/get_lounge_token_batch"),e)},uFa=function(a){a.o=a.B.Ae();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+r6(a.o))},qFa=function(a){B7(a);
a.B=new t7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.xL,a));uFa(a);a.C=dEa(g.yH("yt-remote-automatic-screen-cache")||[]);B7(a);a.info("Initializing automatic screens: "+r6(a.C));a.A=new w7(a.F,(0,g.B)(a.Ae,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},A7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=u6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.xH("yt-remote-automatic-screen-cache",(0,g.J)(a.C,bEa)));B7(a);a.D[b.uuid]=b.id;g.xH("yt-remote-device-id-map",a.D,31536E3);return b},B7=function(a){a.D=g.yH("yt-remote-device-id-map")||{}},C7=function(a,b,c){g.$F.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},D7=function(a,b){m7(a.M,b)},E7=function(a,b){C7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.SX,this);this.D=(0,g.B)(this.aW,this);this.C=g.rE((0,g.B)(function(){vFa(this,null)},this),12E4)},wFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){D7(this,"Failed to send message: getMdxSessionStatus.")},a)):D7(a,"Sending yt message without session: "+g.Hg(b))},vFa=function(a,b){g.tE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.mq,a),d=(0,g.B)(a.Fe,a);a.oA(b,c,d,5)}}else a.Fe(Error("Waiting for session status timed out."))},F7=function(a,b,c){C7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.VX,this);this.o=g.A},xFa=function(a){a.o=a.J.KG(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.mq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Fe(a)},a))},yFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}nEa()&&(b.env_useStageMdx=1);return g.Xg(b)},G7=function(a,b){C7.call(this,a,b,"ManualSession");
this.o=g.rE((0,g.B)(this.mk,this,null),150)},H7=function(a,b,c,d){g.$F.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.AU,this)},zFa=function(a,b){return b?g.Ia(a.B,function(a){return p6(b,a.label)},a):null},I7=function(a){m7("Controller",a)},cFa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},J7=function(a){return a.D||!!a.B.length||!!a.o},K7=function(a,b,c){b!=a.o&&(g.lf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.oE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.mk(null)):a.V("yt-remote-cast2-session-change",null))},AFa=function(a){var b=a.A.JG(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(a){c&&p6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=zFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},GFa=function(a,b,c,d,e,f,k){BFa()?CFa(b,e,f,k)&&(M7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?DFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?DFa(a,c):(N7("Failed to load cast API: "+d),O7(!1),M7(!1),g.zH("yt-remote-cast-available"),g.zH("yt-remote-cast-receiver"),EFa(),
c(!1))},d?rEa():F6("CriOS")?wEa():F6("Android")&&F6("Chrome/")&&window.navigator.presentation?xEa():window.chrome&&window.navigator.presentation&&!F6("Edge")?(G6(),C6(FFa.map(uEa))):D6())):L7("Cannot initialize because not running Chrome")},EFa=function(){L7("dispose");
var a=P7();a&&a.dispose();g.ta("yt.mdx.remote.cloudview.instance_",null,void 0);HFa(!1);g.nG(Q7);Q7.length=0},R7=function(){return!!g.yH("yt-remote-cast-installed")},IFa=function(){var a=g.yH("yt-remote-cast-receiver");
return a?a.friendlyName:null},JFa=function(){L7("clearCurrentReceiver");
g.zH("yt-remote-cast-receiver")},KFa=function(){return R7()?P7()?P7().getCastSession():(N7("getCastSelector: Cast is not initialized."),null):(N7("getCastSelector: Cast API is not installed!"),null)},T7=function(){R7()?P7()?S7()?(L7("Requesting cast selector."),P7().requestSession()):(L7("Wait for cast API to be ready to request the session."),Q7.push(g.mG("yt-remote-cast2-api-ready",T7))):N7("requestCastSelector: Cast is not initialized."):N7("requestCastSelector: Cast API is not installed!")},U7=
function(a,b){S7()?P7().setConnectedScreenStatus(a,b):N7("setConnectedScreenStatus called before ready.")},BFa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.NI||a},LFa=function(a,b){P7().init(a,b)},CFa=function(a,b,c,d){var e=!1;
P7()||(a=new H7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.xH("yt-remote-cast-available",a);g.qG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){L7("onReceiverSelected: "+a.friendlyName);
g.xH("yt-remote-cast-receiver",a);g.qG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){L7("onReceiverResumed: "+a.friendlyName);
g.xH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){L7("onSessionChange: "+q6(a));
a||g.zH("yt-remote-cast-receiver");g.qG("yt-remote-cast2-session-change",a)}),g.ta("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
L7("cloudview.createSingleton_: "+e);return e},P7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},DFa=function(a,b){O7(!0);
M7(!1);LFa(a,function(a){a?(HFa(!0),g.pG("yt-remote-cast2-api-ready")):(N7("Failed to initialize cast API."),O7(!1),g.zH("yt-remote-cast-available"),g.zH("yt-remote-cast-receiver"),EFa());b(a)})},L7=function(a){m7("cloudview",a)},N7=function(a){m7("cloudview",a)},O7=function(a){L7("setCastInstalled_ "+a);
g.xH("yt-remote-cast-installed",a)},S7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},HFa=function(a){L7("setApiReady_ "+a);
g.ta("yt.mdx.remote.cloudview.apiReady_",a,void 0)},M7=function(a){g.ta("yt.mdx.remote.cloudview.initializing_",a,void 0)},V7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.ag=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},W7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.ag=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},X7=function(a){return a.rb()?((0,g.H)()-a.G)/1E3:0},Y7=function(a,b){a.H=b;
a.G=(0,g.H)()},Z7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},$7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&W7(a)},a8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.A);b.hasPrevious=a.ag;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},c8=function(a,b){g.$F.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.PC;this.B=this.A=null;this.J=(0,g.B)(this.RR,this);this.G=(0,g.B)(this.an,this);this.H=(0,g.B)(this.QR,this);this.K=(0,g.B)(this.dS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.tx,this),MFa(this))):c=3;0!=c&&(b?this.tx(c):g.rE((0,g.B)(function(){this.tx(c)},this),0));
var d=KFa();d&&b8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},d8=function(a){return new V7(a.C.getPlayerContextData())},MFa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Ca(this.vU,a),this))},a)},NFa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},e8=function(a,b){50>a.D.yc()&&g.RC(a.D,b)},g8=function(a,b,c){var d=d8(a);
Y7(d,c);-1E3!=d.o&&(d.o=b);f8(a,d)},h8=function(a,b,c){a.C.sendMessage(b,c)},f8=function(a,b){NFa(a);
a.C.setPlayerContextData(a8(b));MFa(a)},b8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.an(null));
a.B=b;a.B&&(m7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.an(a.B.media[0]))},OFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=d8(a);b.contentId!=d.videoId&&m7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;Y7(d,a.A.getEstimatedTime());f8(a,d)}else m7("CP","No cast media video. Ignoring state update.")},i8=function(a,b,c){return(0,g.B)(function(a){this.oc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.oc("Retrying "+b+" using MDx browser channel."),h8(this,b,c))},a)},j8=function(a,b,c){g.$F.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.U=[];this.C=this.G=this.B=this.jb=this.o=null;this.pa=a;this.U.push(g.JF(window,"beforeunload",(0,g.B)(this.aL,this)));this.A=[];this.jb=new V7;this.ba=b.id;this.o=PFa(this,c);this.o.subscribe("handlerOpened",this.VR,this);this.o.subscribe("handlerClosed",this.SR,this);this.o.subscribe("handlerError",this.TR,this);this.o.subscribe("handlerMessage",this.UR,this);bFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.AH()&&g.xH("yt-remote-session-video-id",a)},this)},k8=function(a){m7("conn",a)},PFa=function(a,b){return new g7(j7(a.pa,"/bc"),b)},l8=function(a,b){a.V("proxyStateChange",b)},QFa=function(a){a.D=g.rE((0,g.B)(function(){k8("Connecting timeout");
this.F(1)},a),2E4)},m8=function(a){g.tE(a.D);
a.D=window.NaN},n8=function(a){g.tE(a.M);
a.M=window.NaN},RFa=function(a){o8(a);
a.L=g.rE((0,g.B)(function(){p8(this,"getNowPlaying")},a),2E4)},o8=function(a){g.tE(a.L);
a.L=window.NaN},TFa=function(a,b){b&&(m8(a),n8(a));
b==(h7(a.o)&&(0,window.isNaN)(a.D))?b&&(l8(a,1),p8(a,"getSubtitlesTrack")):b?(a.Z()&&a.jb.reset(),l8(a,1),p8(a,"getNowPlaying"),SFa(a)):a.F(1)},UFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Yb(b.params)?a.jb.A=null:a.jb.A=b.params,a.V("remotePlayerChange"))},VFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;$7(a.jb,c,d);a.V("remoteQueueChange")},XFa=function(a,b){b.params=b.params||{};
VFa(a,b);WFa(a,b);a.V("autoplayDismissed")},WFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Y7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.o&&(c=-1E3);a.jb.o=c;c=Number(b.params.loadedTime);a.jb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.J=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.jb.o?RFa(a):o8(a);
a.V("remotePlayerChange")},YFa=function(a,b){if(-1E3!=a.jb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);Y7(a.jb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},ZFa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.V("remotePlayerChange")},$Fa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},aGa=function(a,b){var c="true"==b.params.hasNext;
a.jb.ag="true"==b.params.hasPrevious;a.jb.hasNext=c;a.V("previousNextChange")},SFa=function(a){g.tE(a.K);
a.K=g.rE((0,g.B)(a.F,a,1),864E5)},p8=function(a,b,c){c?k8("Sending: action="+b+", params="+g.Hg(c)):k8("Sending: action="+b);
a.o.sendMessage(b,c)},q8=function(a){q7.call(this,"ScreenServiceProxy");
this.kd=a;this.A=[];this.A.push(this.kd.$_s("screenChange",(0,g.B)(this.QX,this)));this.A.push(this.kd.$_s("onlineScreenChange",(0,g.B)(this.ST,this)))},fGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.kE("MDX_CONFIG")||b;fEa();y6();r8||(r8=new i7(b?b.loungeApiHost:void 0),nEa()&&(r8.o="/api/loungedev"));s8||(s8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ta("yt.mdx.remote.deferredProxies_",s8,void 0));bGa();var c=t8();if(!c){var d=new z7(r8);g.ta("yt.mdx.remote.screenService_",d,void 0);c=t8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);GFa(a,d,function(a){a?u8()&&U7(u8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.qG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ta("yt.mdx.remote.initialized_",!0,void 0),v8("Initializing: "+g.Hg(b)),w8.push(g.mG("yt-remote-cast2-availability-change",function(){g.qG("yt-remote-receiver-availability-change")})),w8.push(g.mG("yt-remote-cast2-receiver-selected",function(){x8(null);
g.qG("yt-remote-auto-connect","cast-selector-receiver")})),w8.push(g.mG("yt-remote-cast2-receiver-resumed",function(){g.qG("yt-remote-receiver-resumed","cast-selector-receiver")})),w8.push(g.mG("yt-remote-cast2-session-change",cGa)),w8.push(g.mG("yt-remote-connection-change",function(a){a?U7(u8(),"YouTube TV"):y8()||(U7(null,null),JFa())})),a=z8(),b.isAuto&&(a.id+="#dial"),g.oE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),v8(" -- with channel params: "+
g.Hg(a)),dGa(a),c.start(),u8()||eGa())},hGa=function(){var a=gGa();
R7()&&g.yH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},gGa=function(){var a=t8().kd.$_gos();
var b=A8();b&&B8()&&(t6(a,b)||a.push(b));return eEa(a)},C8=function(){var a=iGa();
!a&&R7()&&IFa()&&(a={key:"cast-selector-receiver",name:IFa()});return a},iGa=function(){var a=gGa(),b=A8();
b||(b=y8());return g.Ia(a,function(a){return b&&p6(b,a.key)?!0:!1})},A8=function(){var a=u8();
if(!a)return null;var b=t8().Ae();return u6(b,a)},cGa=function(a){v8("remote.onCastSessionChange_: "+q6(a));
if(a){var b=A8();b&&b.id==a.id?U7(b.id,"YouTube TV"):(b&&D8(),E8(a,1))}else B8()&&D8()},D8=function(){S7()?P7().stopSession():N7("stopSession called before API ready.");
var a=B8();a&&(a.disconnect(1),F8(null))},G8=function(){var a=B8();
return!!a&&3!=a.getProxyState()},v8=function(a){m7("remote",a)},t8=function(){if(!H8){var a=g.y("yt.mdx.remote.screenService_");
H8=a?new q8(a):null}return H8},u8=function(){return g.y("yt.mdx.remote.currentScreenId_")},jGa=function(a){g.ta("yt.mdx.remote.currentScreenId_",a,void 0)},kGa=function(){return g.y("yt.mdx.remote.connectData_")},x8=function(a){g.ta("yt.mdx.remote.connectData_",a,void 0)},B8=function(){return g.y("yt.mdx.remote.connection_")},F8=function(a){var b=B8();
x8(null);a||jGa("");g.ta("yt.mdx.remote.connection_",a,void 0);s8&&((0,g.D)(s8,function(b){b(a)}),s8.length=0);
b&&!a?g.qG("yt-remote-connection-change",!1):!b&&a&&g.qG("yt-remote-connection-change",!0)},y8=function(){var a=g.AH();
if(!a)return null;var b=t8().Ae();return u6(b,a)},E8=function(a,b){A8()&&A8();
jGa(a.id);var c=new j8(r8,a,z8());c.connect(b,kGa());c.subscribe("beforeDisconnect",function(a){g.qG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){B8()&&F8(null)});
F8(c)},eGa=function(){var a=y8();
a?(v8("Resume connection to: "+q6(a)),E8(a,0)):(z6(),JFa(),v8("Skipping connecting because no session screen found."))},bGa=function(){var a=z8();
if(g.Yb(a)){a=x6();var b=g.yH("yt-remote-session-name")||"",c=g.yH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ta("yt.mdx.remote.channelParams_",a,void 0)}},z8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},dGa=function(a){a?(g.xH("yt-remote-session-app",a.app),g.xH("yt-remote-session-name",a.name)):(g.zH("yt-remote-session-app"),g.zH("yt-remote-session-name"));
g.ta("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.L.call(this);
this.D=a;this.A=b;this.B=new g.XF(this);g.M(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.lT);this.B.R(b,"captionschanged",this.PR);this.B.R(b,"captionssettingschanged",this.RF);this.B.R(b,"videoplayerreset",this.nq);this.B.R(b,"mdxautoplaycancel",this.aK);this.U=this.B.R(b,"onVolumeChange",this.WD);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.kE,this);c.subscribe("remotePlayerChange",this.cn,this);c.subscribe("remoteQueueChange",this.nq,this);c.subscribe("autoplayUpNext",this.ID,
this);c.subscribe("previousNextChange",this.hE,this);c.subscribe("nowAutoplaying",this.ZD,this);c.subscribe("autoplayDismissed",this.HD,this);this.suggestion=null;this.J=new g.FP(64);this.C=new g.V(this.NF,500,this);g.M(this,this.C);this.F=new g.V(this.OF,1E3,this);g.M(this,this.F);this.L=new H6(this.rX,0,this);g.M(this,this.L);this.G={};this.M=new g.V(this.sG,1E3,this);g.M(this,this.M);this.K=new g.wl(this.TP,1E3,this);g.M(this,this.K);this.O=g.A;this.RF();this.nq();this.cn()},J8=function(a,b){var c=
a.D,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.player.V("progresssync",b,d)},lGa=function(a){J8(a,0);
a.C.stop();K8(a,new g.FP(64))},M8=function(a,b){if(L8(a)&&!a.H){var c=null;
b&&(c={style:a.A.Yi()},g.fc(c,b));a.o.CF(a.A.getVideoData(1).videoId,c);a.G=d8(a.o).A}},N8=function(a,b){var c=a.A.ig();
if(c){var d=c.ye();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.dk;f=VDa(f);var n=d8(c);l=l||0;var p={videoId:k,currentIndex:l};$7(n,k,l);g.u(b)&&(Y7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Hg(f));h8(c,"setPlaylist",p);e||f8(c,n);K8(a,new g.FP(1))},mGa=function(a,b){if(b){var c=a.A.Bc("captions","tracklist",{hB:1});
c&&c.length?(a.A.Ud("captions","track",b),a.H=!1):(a.A.uk("captions"),a.H=!0)}else a.A.Ud("captions","track",{})},L8=function(a){return d8(a.o).videoId==a.A.getVideoData(1).videoId},K8=function(a,b){a.F.stop();
var c=a.J;if(!g.LP(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.XT(a.A,d);a.J=b;nGa(a.D,c,b)}},O8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.vra()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.XU(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);oGa(this,g.ST(a))},oGa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Bc("remote","currentReceiver").name};
c=g.X(b,128)?g.PU("Error on $RECEIVER_NAME",c):b.rb()||g.X(b,4)?g.PU("Playing on $RECEIVER_NAME",c):g.PU("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},P8=function(a,b){g.wY.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},Q8=function(a){g.yU.call(this,a);
this.A={key:s6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.FP(64);this.J=0;this.G=-1;if(!g.lN(g.Y(this.player))){a=this.player;var b=g.oI(a);b&&(b=b.Rm())&&(b=new P8(a,b),g.M(this,b));b=new O8(a);g.M(this,b);g.mU(a,b.element,4)}},nGa=function(a,b,c){a.F=c;
a.player.V("presentingplayerstatechange",new g.QP(c,b))},R8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)D8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.ig();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Qa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.dk,index:Math.max(a.player.mC(),0),currentTime:0==f?void 0:f};(d=VDa(d))&&(c.locationInfo=d);d=c}else d=null;v8("Connecting to: "+g.Hg(b));"cast-selector-receiver"==b.key?(x8(d||null),S7()?P7().setLaunchParams(d||
null):N7("setLaunchParams called before ready.")):!d&&G8()&&u8()==b.key?g.qG("yt-remote-connection-change",!0):(D8(),x8(d||null),d=t8().Ae(),(d=u6(d,b.key))&&E8(d,1))}},DEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},R6={"'":"\\'"},pGa={},aEa={fZ:"atp",K3:"ska",b3:"que",n2:"mus",G3:"sus",r0:"dsp"};
n6.prototype.Co=function(){var a=new n6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var A6,w6="",E6=B6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",vEa=B6("loadCastFramework")||B6("loadCastApplicationFramework"),FFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(H6,g.L);g.h=H6.prototype;g.h.VK=function(a){this.C=arguments;this.o=!1;this.Ea?this.B=(0,g.H)()+this.Bd:this.Ea=g.Cg(this.D,this.Bd)};
g.h.stop=function(){this.Ea&&(g.Dg(this.Ea),this.Ea=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();H6.fa.X.call(this)};
g.h.WK=function(){this.B?(this.Ea=g.Cg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};I6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
I6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=J6.prototype;g.h.Fi=null;g.h.Jf=!1;g.h.kl=null;g.h.jx=null;g.h.Ok=null;g.h.Uj=null;g.h.wh=null;g.h.Wh=null;g.h.gj=null;g.h.Tc=null;g.h.zn=0;g.h.Kf=null;g.h.tr=null;g.h.xh=null;g.h.dm=-1;g.h.iF=!0;g.h.oi=!1;g.h.xt=0;g.h.Cq=null;var BEa={},M6={};g.h=J6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.oW=function(a){a=a.target;var b=this.Cq;b&&3==g.Kx(a)?b.Wl():this.DG(a)};
g.h.DG=function(a){try{if(a==this.Tc)a:{var b=g.Kx(this.Tc),c=this.Tc.A,d=this.Tc.getStatus();if(g.Hd&&!g.rc(10)||g.Jd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.qf&&!g.Ox(this.Tc))break a;this.oi||4!=b||7==c||(8==c||0>=d?this.o.Cf(3):this.o.Cf(2));T6(this);var e=this.Tc.getStatus();this.dm=e;var f=g.Ox(this.Tc);(this.Jf=200==e)?(4==b&&P6(this),this.D?(CEa(this,b,f),g.qf&&this.Jf&&3==b&&(this.Y.W(this.A,"tick",this.lW),this.A.start())):O6(this,f),this.Jf&&!this.oi&&(4==b?this.o.lq(this):
(this.Jf=!1,L6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.xh=3,N6(13)):(this.xh=0,N6(14)),P6(this),Q6(this))}}catch(k){this.Tc&&g.Ox(this.Tc)}finally{}};
g.h.lW=function(){var a=g.Kx(this.Tc),b=g.Ox(this.Tc);this.zn<b.length&&(T6(this),CEa(this,a,b),this.Jf&&4!=a&&L6(this))};
g.h.xV=function(a){S6((0,g.B)(this.wV,this,a),0)};
g.h.wV=function(a){this.oi||(T6(this),O6(this,a),L6(this))};
g.h.tE=function(a){S6((0,g.B)(this.vV,this,a),0)};
g.h.vV=function(a){this.oi||(P6(this),this.Jf=a,this.o.lq(this),this.o.Cf(4))};
g.h.cancel=function(){this.oi=!0;P6(this)};
g.h.OV=function(){this.kl=null;var a=(0,g.H)();0<=a-this.jx?(2!=this.Uj&&this.o.Cf(3),P6(this),this.xh=2,N6(18),Q6(this)):FEa(this,this.jx-a)};g.h=IEa.prototype;g.h.vt=null;g.h.Ge=null;g.h.Dq=!1;g.h.zA=null;g.h.Qo=null;g.h.pu=null;g.h.wt=null;g.h.Ye=null;g.h.Lg=-1;g.h.Zl=null;g.h.rl=null;g.h.connect=function(a){this.wt=a;a=V6(this.o,null,this.wt);N6(3);this.zA=(0,g.H)();var b=this.o.H;null!=b?(this.Zl=b[0],(this.rl=b[1])?(this.Ye=1,JEa(this)):(this.Ye=2,X6(this))):(m6(a,"MODE","init"),this.Ge=new J6(this,void 0,void 0,void 0),this.Ge.Fi=this.vt,K6(this.Ge,a,!1,null,!0),this.Ye=0)};
g.h.bK=function(a){if(a)this.Ye=2,X6(this);else{N6(4);var b=this.o;b.Wf=b.nh.Lg;d7(b,9)}a&&this.Cf(2)};
g.h.Gs=function(a){return this.o.Gs(a)};
g.h.abort=function(){this.Ge&&(this.Ge.cancel(),this.Ge=null);this.Lg=-1};
g.h.yA=function(){return!1};
g.h.lE=function(a,b){this.Lg=a.dm;if(0==this.Ye)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Wf=this.Lg;d7(c,2);return}this.Zl=c[0];this.rl=c[1]}else c=this.o,c.Wf=this.Lg,d7(c,2);else if(2==this.Ye)if(this.Dq)N6(7),this.pu=(0,g.H)();else if("11111"==b){if(N6(6),this.Dq=!0,this.Qo=(0,g.H)(),c=this.Qo-this.zA,!g.Hd||g.rc(10)||500>c)this.Lg=200,this.Ge.cancel(),N6(12),W6(this.o,this,!0)}else N6(8),this.Qo=this.pu=(0,g.H)(),this.Dq=!1};
g.h.lq=function(){this.Lg=this.Ge.dm;if(this.Ge.Jf)0==this.Ye?this.rl?(this.Ye=1,JEa(this)):(this.Ye=2,X6(this)):2==this.Ye&&((!g.Hd||g.rc(10)?!this.Dq:200>this.pu-this.Qo)?(N6(11),W6(this.o,this,!1)):(N6(12),W6(this.o,this,!0)));else{0==this.Ye?N6(9):2==this.Ye&&N6(10);var a=this.o;a.Wf=this.Lg;d7(a,2)}};
g.h.pn=function(){return this.o.pn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Cf=function(a){this.o.Cf(a)};g.h=Y6.prototype;g.h.Hl=null;g.h.fe=null;g.h.xc=null;g.h.qt=null;g.h.Uo=null;g.h.Sy=null;g.h.ip=null;g.h.Xm=0;g.h.hR=0;g.h.Ad=null;g.h.rh=null;g.h.yg=null;g.h.si=null;g.h.nh=null;g.h.rr=null;g.h.kk=-1;g.h.vB=-1;g.h.Wf=-1;g.h.Jj=0;g.h.xj=0;g.h.ri=8;var e7=new g.Pf;g.C(LEa,g.nf);g.C(MEa,g.nf);g.C(NEa,g.nf);g.h=Y6.prototype;g.h.connect=function(a,b,c,d,e){N6(0);this.qt=b;this.Hl=c||{};d&&g.u(e)&&(this.Hl.OSID=d,this.Hl.OAID=e);this.F?(S6((0,g.B)(this.nz,this,a),100),REa(this)):this.nz(a)};
g.h.nz=function(a){this.nh=new IEa(this);this.nh.vt=null;this.nh.A=this.D;this.nh.connect(a)};
g.h.yA=function(){return 0==this.o};
g.h.rE=function(a){this.rh=null;UEa(this,a)};
g.h.qE=function(){this.yg=null;this.xc=new J6(this,this.B,"rpc",this.G);this.xc.Fi=null;this.xc.xt=0;var a=this.Sy.clone();g.dn(a,"RID","rpc");g.dn(a,"SID",this.B);g.dn(a,"CI",this.rr?"0":"1");g.dn(a,"AID",this.kk);Z6(this,a);if(!g.Hd||g.rc(10))g.dn(a,"TYPE","xmlhttp"),K6(this.xc,a,!0,this.ip,!1);else{g.dn(a,"TYPE","html");var b=this.xc,c=!!this.ip;b.Uj=3;b.wh=l6(a.clone());EEa(b,c)}};
g.h.lE=function(a,b){if(0!=this.o&&(this.xc==a||this.fe==a))if(this.Wf=a.dm,this.fe==a&&3==this.o)if(7<this.ri){try{var c=this.D.parse(b)}catch(f){c=null}if(g.wa(c)&&3==c.length)if(0==c[0])a:{if(!this.yg){if(this.xc)if(this.xc.Ok+3E3<this.fe.Ok)a7(this),this.xc.cancel(),this.xc=null;else break a;c7(this);N6(19)}}else this.vB=c[1],0<this.vB-this.kk&&37500>c[2]&&this.rr&&0==this.xj&&!this.si&&(this.si=S6((0,g.B)(this.KR,this),6E3));else d7(this,11)}else b!=pGa.h_.o&&d7(this,11);else if(this.xc==a&&
a7(this),!g.F(b)){c=this.D.parse(b);g.wa(c);for(var d=0;d<c.length;d++){var e=c[d];this.kk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.ip=e[2],e=e[3],null!=e?this.ri=e:this.ri=6,this.o=3,this.Ad&&this.Ad.fz(),this.Sy=V6(this,this.pn()?this.ip:null,this.qt),VEa(this)):"stop"==e[0]&&d7(this,7):3==this.o&&("stop"==e[0]?d7(this,7):"noop"!=e[0]&&this.Ad&&this.Ad.ez(e),this.xj=0)}}};
g.h.KR=function(){null!=this.si&&(this.si=null,this.xc.cancel(),this.xc=null,c7(this),N6(20))};
g.h.lq=function(a){if(this.xc==a){a7(this);this.xc=null;var b=2}else if(this.fe==a)this.fe=null,b=1;else return;this.Wf=a.dm;if(0!=this.o)if(a.Jf)1==b?(b=(0,g.H)()-a.Ok,e7.dispatchEvent(new MEa(e7,a.gj?a.gj.length:0,b,this.Jj)),$6(this),this.C.length=0):VEa(this);else{var c=a.xh,d;if(!(d=3==c||7==c||0==c&&0<this.Wf)){if(d=1==b)this.fe||this.rh||1==this.o||2<=this.Jj?d=!1:(this.rh=S6((0,g.B)(this.rE,this,a),WEa(this,this.Jj)),this.Jj++,d=!0);d=!(d||2==b&&c7(this))}if(d)switch(c){case 1:d7(this,5);
break;case 4:d7(this,10);break;case 3:d7(this,6);break;case 7:d7(this,12);break;default:d7(this,2)}}};
g.h.xK=function(a){if(!g.Ma(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.eX=function(a){a?N6(2):(N6(1),XEa(this,8))};
g.h.Gs=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Ex;a.H=!1;return a};
g.h.isActive=function(){return!!this.Ad&&this.Ad.isActive(this)};
g.h.Cf=function(a){e7.dispatchEvent(new NEa(e7,a))};
g.h.pn=function(){return!(!g.Hd||g.rc(10))};
g.h=YEa.prototype;g.h.fz=function(){};
g.h.ez=function(){};
g.h.dz=function(){};
g.h.rs=function(){};
g.h.dA=function(){return{}};
g.h.isActive=function(){return!0};g.C(f7,g.L);g.h=f7.prototype;g.h.oV=function(){this.Bd=Math.min(3E5,2*this.Bd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Bd+15E3*Math.random();g.Du(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Bd=5E3};g.C(g7,YEa);g.h=g7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Yd=function(a){return this.B.Yd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.lf(this.B),aFa(this),g.lf(this.A),this.A=null)};
g.h.ka=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Y6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Ad=null);d.Ad=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.kk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):h7(this)&&SEa(this.o,c)};
g.h.fz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)SEa(this.o,a[b])}this.V("handlerOpened")};
g.h.dz=function(a){var b=2==a&&401==this.o.Wf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.rs=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.dA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.fc(a,this.D);return a};
g.h.ez=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),QEa(this.o)):this.V("handlerMessage",new ZEa(a[0],a[1]))};
g.h.MX=function(){this.A.isActive();var a=this.o,b=0;a.xc&&b++;a.fe&&b++;0!=b||this.connect(this.D,this.C)};i7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
i7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
i7.prototype.D=function(a){a(Error("request timed out"))};var iFa=(0,g.H)(),l7=null,o7=Array(50),n7=-1,p7=!1;g.C(q7,g.$F);q7.prototype.Ae=function(){return this.o};
q7.prototype.contains=function(a){return!!t6(this.o,a)};
q7.prototype.get=function(a){return a?u6(this.o,a):null};
q7.prototype.info=function(a){m7(this.G,a)};g.C(r7,g.$F);var qGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=r7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ea)&&this.IG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ea)||(g.tE(this.Ea),this.Ea=window.NaN)};
g.h.X=function(){this.stop();r7.fa.X.call(this)};
g.h.IG=function(){this.Ea=window.NaN;this.o=g.IE(j7(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.OX,this),onError:(0,g.B)(this.NX,this),Fd:(0,g.B)(this.PX,this)})};
g.h.OX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new o6(c))};
g.h.NX=function(a){this.o=null;a.status&&404==a.status?this.A>=qGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=qGa[this.A],this.Ea=g.rE((0,g.B)(this.IG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.PX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(t7,q7);g.h=t7.prototype;g.h.start=function(){s7(this)&&this.V("screenChange");!g.yH("yt-remote-lounge-token-expiration")&&mFa(this);g.tE(this.A);this.A=g.rE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){s7(this);jFa(this,a);u7(this,!1);this.V("screenChange");b(a);a.token||mFa(this)};
g.h.remove=function(a,b){var c=s7(this);lFa(this,a)&&(u7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.lr=function(a,b,c,d){var e=s7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,u7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.tE(this.A);t7.fa.X.call(this)};
g.h.jL=function(a){s7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}u7(this,!b);b&&m7(this.G,"Missed "+b+" lounge tokens.")};
g.h.iL=function(a){m7(this.G,"Requesting lounge tokens failed: "+a)};g.C(w7,g.$F);g.h=w7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.yH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?y7(this):(this.C=(0,g.H)()+3E5,g.xH("yt-remote-fast-check-period",this.C),this.mw())};
g.h.isEmpty=function(){return g.Yb(this.o)};
g.h.update=function(){v7("Updating availability on schedule.");var a=this.F(),b=g.Ib(this.o,function(b,d){return b&&!!u6(a,d)},this);
x7(this,b)};
g.h.X=function(){g.tE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);w7.fa.X.call(this)};
g.h.mw=function(){g.tE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=pFa(this);if(g.Nb(a)){var b=j7(this.D,"/pairing/get_screen_availability");this.A=k7(this.D,b,{lounge_token:g.Qb(a).join(",")},(0,g.B)(this.WU,this,a),(0,g.B)(this.VU,this))}else x7(this,{}),y7(this)};
g.h.WU=function(a,b){this.A=null;var c=g.Qb(pFa(this));if(g.eb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x7(this,d);y7(this)}else this.oc("Changing Screen set during request."),this.mw()};
g.h.VU=function(a){this.oc("Screen availability failed: "+a);this.A=null;y7(this)};
g.h.oc=function(a){m7("OnlineScreenService",a)};g.C(z7,q7);g.h=z7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.lr=function(a,b,c,d){this.B.contains(a)?this.B.lr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,m7(this.G,a),d(Error(a)))};
g.h.Ae=function(a){return a?this.o:g.Ua(this.o,(0,g.Vd)(this.C,function(a){return!this.contains(a)},this))};
g.h.JG=function(){return(0,g.Vd)(this.Ae(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.KG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new r7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.lf(f);d(A7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.RX=function(a,b,c,d){g.IE(j7(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new o6(d.screen||{});if(!e.name||tFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);tFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(A7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Fd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.lf(this.B);g.lf(this.A);z7.fa.X.call(this)};
g.h.xL=function(){uFa(this);this.V("screenChange");this.A.update()};
z7.prototype.dispose=z7.prototype.dispose;g.C(C7,g.$F);g.h=C7.prototype;g.h.mq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Fe=function(a){this.ka()||(a&&D7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){m7(this.M,a)};
g.h.MG=function(){return null};
g.h.yw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){D7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.yw("");C7.fa.X.call(this)};g.C(E7,C7);g.h=E7.prototype;g.h.xw=function(a){if(this.o){if(this.o==a)return;D7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);wFa(this)};
g.h.mk=function(a){this.info("launchWithParams no-op for Cast: "+g.Hg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Fe()},this),(0,g.B)(function(){this.Fe(Error("Failed to stop receiver app."))},this)):this.Fe(Error("Stopping cast device witout session."))};
g.h.yw=g.A;g.h.X=function(){this.info("disposeInternal");g.tE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;E7.fa.X.call(this)};
g.h.aW=function(a,b){if(!this.ka())if(b){var c=g.yx(b);if(g.za(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hg(c));switch(d){case "mdxSessionStatus":vFa(this,c.screenId);break;default:D7(this,"Unknown youtube message: "+d)}}else D7(this,"Unable to parse message.")}else D7(this,"No data in message.")};
g.h.oA=function(a,b,c,d){sFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(D7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.rE((0,g.B)(this.oA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.MG=function(){return this.o};
g.h.SX=function(a){this.ka()||a||(D7(this,"Cast session died."),this.Fe())};g.C(F7,C7);g.h=F7.prototype;g.h.xw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.mk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.tE(this.F);this.C?this.C.stop((0,g.B)(this.Fe,this,null),(0,g.B)(this.Fe,this,"Failed to stop DIAL device.")):this.Fe()};
g.h.X=function(){this.o();this.o=g.A;g.tE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;F7.fa.X.call(this)};
g.h.VX=function(a){this.ka()||a||(D7(this,"DIAL session died."),this.o(),this.o=g.A,this.Fe())};
g.h.bu=function(a){this.K=s6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,yFa(this));a(b);xFa(this)}else this.G=(0,g.B)(function(){g.tE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,yFa(this));a(b);xFa(this)},this),this.F=g.rE((0,g.B)(function(){this.G()},this),100)};
g.h.MM=function(a,b,c){sFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.mq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.bu(b,c)},this),(0,g.B)(function(a){D7(this,"Failed to get DIAL screen: "+a);
this.bu(b,c)},this))};g.C(G7,C7);G7.prototype.stop=function(){this.Fe()};
G7.prototype.xw=g.A;G7.prototype.mk=function(){g.tE(this.o);this.o=window.NaN;var a=u6(this.J.Ae(),this.A.label);a?this.mq(a):this.Fe(Error("No such screen"))};
G7.prototype.X=function(){g.tE(this.o);this.o=window.NaN;G7.fa.X.call(this)};g.C(H7,g.$F);g.h=H7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.nE,this),(0,g.B)(this.EU,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.uS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.C),fFa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.LG,this)),this.B=AFa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.oc("Failed to set initial custom receivers: "+g.Hg(a))},this)),this.V("yt-remote-cast2-availability-change",J7(this)),b(!0))},this),(0,g.B)(function(a){this.oc("Failed to initialize API: "+g.Hg(a));
b(!1)},this))};
g.h.MW=function(a,b){I7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)I7("Unsetting old screen status: "+this.o.A.friendlyName),K7(this,null)}if(a&&b){if(!this.o){c=u6(this.A.Ae(),a);if(!c){I7("setConnectedScreenStatus: Unknown screen.");return}var d=zFa(this,c);d||(I7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.oc("Failed to set initial custom receivers: "+g.Hg(a))},this)));
I7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);K7(this,new G7(this.A,d),!0)}this.o.yw(b)}else I7("setConnectedScreenStatus: no screen.")};
g.h.NW=function(a){this.ka()?this.oc("Setting connection data on disposed cast v2"):this.o?this.o.mk(a):this.oc("Setting connection data without a session")};
g.h.UX=function(){this.ka()?this.oc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),K7(this,null)):I7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.nE,this),(0,g.B)(this.aV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.LG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Sa(g.y("yt.mdx.remote.debug.handlers_")||[],cFa);g.lf(this.o);H7.fa.X.call(this)};
g.h.oc=function(a){m7("Controller",a)};
g.h.oE=function(a,b){this.o==a&&(b||K7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.AU=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),I7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)I7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{I7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:K7(this,
new G7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:K7(this,new F7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:K7(this,new E7(this.A,a));break;default:this.oc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.oc("Stopping receiver w/o session: "+a.friendlyName)}else this.oc("onReceiverAction_ called without receiver.")};
g.h.uS=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.oc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.oc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return I7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.oc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);K7(this,new F7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.MM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.bu,b))};
g.h.nE=function(a){if(!this.ka()){I7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)I7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),K7(this,new E7(this.A,b),!0);else{this.oc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=u6(this.A.Ae(),c.label);
d&&p6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(I7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.o),this.o=new E7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.oE,this,this.o)),this.o.mk(null));this.o.xw(a)}}};
g.h.TX=function(){return this.o?this.o.MG():null};
g.h.aV=function(a){this.ka()||(this.oc("Failed to estabilish a session: "+g.Hg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&K7(this,null))};
g.h.EU=function(a){I7("Receiver availability updated: "+a);if(!this.ka()){var b=J7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;J7(this)!=b&&this.V("yt-remote-cast2-availability-change",J7(this))}};
g.h.LG=function(){this.ka()||(this.B=AFa(this),I7("Updating custom receivers: "+g.Hg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.oc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",J7(this)))};
H7.prototype.setLaunchParams=H7.prototype.NW;H7.prototype.setConnectedScreenStatus=H7.prototype.MW;H7.prototype.stopSession=H7.prototype.UX;H7.prototype.getCastSession=H7.prototype.TX;H7.prototype.requestSession=H7.prototype.requestSession;H7.prototype.init=H7.prototype.init;H7.prototype.dispose=H7.prototype.dispose;var Q7=[];g.h=V7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";W7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.ag=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.rb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+X7(this):this.J};
g.h.clone=function(){return new V7(a8(this))};g.C(c8,g.$F);g.h=c8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,i8(this,"play")):h8(this,"play"),g8(this,1,Z7(d8(this))),this.V("remotePlayerChange")):e8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,i8(this,"pause")):h8(this,"pause"),g8(this,2,Z7(d8(this))),this.V("remotePlayerChange")):e8(this,this.pause)};
g.h.HG=function(a){if(1==this.o){if(this.A){var b=d8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,i8(this,"seekTo",{newTime:a}))}else h8(this,"seekTo",{newTime:a});g8(this,3,a);this.V("remotePlayerChange")}else e8(this,g.Ca(this.HG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,i8(this,"stopVideo")):h8(this,"stopVideo");var a=d8(this);a.index=-1;a.videoId="";W7(a);f8(this,a);this.V("remotePlayerChange")}else e8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=d8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){m7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.oc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){m7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.oc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);h8(this,"setVolume",e)}c.muted=b;c.volume=a;f8(this,c)}else e8(this,g.Ca(this.setVolume,a,b))};
g.h.CF=function(a,b){if(1==this.o){var c=d8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Hg(b.style),g.fc(d,c.A));h8(this,"setSubtitlesTrack",d);f8(this,c)}else e8(this,g.Ca(this.CF,a,b))};
g.h.rx=function(a,b){if(1==this.o){h8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lb.id});var c=d8(this);c.audioTrackId=b.Lb.id;f8(this,c)}else e8(this,g.Ca(this.rx,a,b))};
g.h.GG=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"previous")}else e8(this,g.Ca(this.GG,a,b))};
g.h.FG=function(a,b){if(1==this.o){if(a&&b){var c=d8(this);$7(c,a,b);f8(this,c)}h8(this,"next")}else e8(this,g.Ca(this.FG,a,b))};
g.h.Hz=function(){1==this.o?h8(this,"dismissAutoplay"):e8(this,this.Hz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}c8.fa.dispose.call(this)};
g.h.X=function(){NFa(this);this.C=null;this.D.clear();b8(this,null);c8.fa.X.call(this)};
g.h.tx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.SC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.vU=function(a,b){this.V(a,b)};
g.h.RR=function(a){if(!a)this.an(null),b8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=d8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)m7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,f8(this,b)}};
g.h.an=function(a){m7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),OFa(this),this.V("remotePlayerChange")};
g.h.QR=function(a){a?(OFa(this),this.V("remotePlayerChange")):this.an(null)};
g.h.dS=function(){var a=KFa();a&&b8(this,a)};
g.h.oc=function(a){m7("CP",a)};g.C(j8,g.$F);g.h=j8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;Y7(this.jb,m);this.C="UNSUPPORTED";k8("Connecting with setPlaylist and params: "+g.Hg(l));this.o.connect({method:"setPlaylist",
params:g.Hg(l)},a,iEa())}else k8("Connecting without params"),this.o.connect({},a,iEa());QFa(this)};
g.h.dispose=function(){this.ka()||(this.V("beforeDispose"),l8(this,3));j8.fa.dispose.call(this)};
g.h.X=function(){m8(this);o8(this);n8(this);g.tE(this.J);this.J=window.NaN;g.tE(this.K);this.K=window.NaN;this.B=null;g.KF(this.U);this.U.length=0;this.o.dispose();j8.fa.X.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.aL=function(){this.F(2)};
g.h.VR=function(){k8("Channel opened");this.O&&(this.O=!1,n8(this),this.M=g.rE((0,g.B)(function(){k8("Timing out waiting for a screen.");this.F(1)},this),15E3));
mEa($Ea(this.o),this.ba)};
g.h.SR=function(){k8("Channel closed");(0,window.isNaN)(this.D)?z6(!0):z6();this.dispose()};
g.h.TR=function(a){z6();(0,window.isNaN)(this.H())?(k8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,k8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),l8(this,2))};
g.h.UR=function(a){a.params?k8("Received: action="+a.action+", params="+g.Hg(a.params)):k8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.yx(a.params.devices);this.A=(0,g.J)(a,function(a){return new n6(a)});
a=!!g.Ia(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
TFa(this,a);break;case "loungeScreenDisconnected":g.Ta(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
TFa(this,!1);break;case "remoteConnected":var b=new n6(g.yx(a.params.device));g.Ia(this.A,function(a){return b?a.id==b.id:!1})||g.Qa(this.A,b);
break;case "remoteDisconnected":b=new n6(g.yx(a.params.device));g.Ta(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":VFa(this,a);break;case "nowPlaying":XFa(this,a);break;case "onStateChange":WFa(this,a);break;case "onAdStateChange":YFa(this,a);break;case "onVolumeChanged":ZFa(this,a);break;case "onSubtitlesTrackChanged":UFa(this,a);break;case "nowAutoplaying":$Fa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":aGa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:k8("Unrecognized action: "+a.action)}};
g.h.wW=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&p8(this,"getNowPlaying")}};
j8.prototype.subscribe=j8.prototype.subscribe;j8.prototype.unsubscribeByKey=j8.prototype.Yd;j8.prototype.ha=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.H())?h7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
j8.prototype.getProxyState=j8.prototype.ha;j8.prototype.F=function(a){k8("Disconnecting with "+a);m8(this);this.V("beforeDisconnect",a);1==a&&z6();aFa(this.o,a);this.dispose()};
j8.prototype.disconnect=j8.prototype.F;j8.prototype.ga=function(){var a=this.jb;this.B&&(a=this.jb.clone(),$7(a,this.B,a.index));return a8(a)};
j8.prototype.getPlayerContextData=j8.prototype.ga;
j8.prototype.la=function(a){var b=new V7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.tE(this.J),this.J=g.rE((0,g.B)(this.wW,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.o==b.o&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&Z7(this.jb)==Z7(b)&&g.Hg(this.jb.A)==g.Hg(b.A)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
j8.prototype.setPlayerContextData=j8.prototype.la;j8.prototype.Z=function(){var a=this.o.F.id,b=g.Ia(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
j8.prototype.getOtherConnectedRemoteId=j8.prototype.Z;j8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
j8.prototype.getReconnectTimeout=j8.prototype.H;j8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
j8.prototype.getAutoplayMode=j8.prototype.aa;j8.prototype.da=function(){return this.G||""};
j8.prototype.getAutoplayVideoId=j8.prototype.da;j8.prototype.va=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Eu(a.o);a.start()}};
j8.prototype.reconnect=j8.prototype.va;j8.prototype.ia=function(a,b){p8(this,a,b);SFa(this)};
j8.prototype.sendMessage=j8.prototype.ia;g.C(q8,q7);g.h=q8.prototype;g.h.Ae=function(a){return this.kd.$_gs(a)};
g.h.contains=function(a){return!!this.kd.$_c(a)};
g.h.get=function(a){return this.kd.$_g(a)};
g.h.start=function(){this.kd.$_st()};
g.h.add=function(a,b,c){this.kd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.kd.$_r(a,b,c)};
g.h.lr=function(a,b,c,d){this.kd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.kd.$_ubk(this.A[a]);this.A.length=0;this.kd=null;q8.fa.X.call(this)};
g.h.QX=function(){this.V("screenChange")};
g.h.ST=function(){this.V("onlineScreenChange")};
z7.prototype.$_st=z7.prototype.start;z7.prototype.$_gspc=z7.prototype.RX;z7.prototype.$_gsppc=z7.prototype.KG;z7.prototype.$_c=z7.prototype.contains;z7.prototype.$_g=z7.prototype.get;z7.prototype.$_a=z7.prototype.add;z7.prototype.$_un=z7.prototype.lr;z7.prototype.$_r=z7.prototype.remove;z7.prototype.$_gs=z7.prototype.Ae;z7.prototype.$_gos=z7.prototype.JG;z7.prototype.$_s=z7.prototype.subscribe;z7.prototype.$_ubk=z7.prototype.Yd;var r8=null,s8=null,H8=null,w8=[];g.t(I8,g.L);g.h=I8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.C.stop();this.F.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.kE,this);this.o.unsubscribe("remotePlayerChange",this.cn,this);this.o.unsubscribe("remoteQueueChange",this.nq,this);this.o.unsubscribe("autoplayUpNext",this.ID,this);this.o.unsubscribe("previousNextChange",this.hE,this);this.o.unsubscribe("nowAutoplaying",this.ZD,this);this.o.unsubscribe("autoplayDismissed",this.HD,this);this.o=this.D=null};
g.h.FC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(L8(this)){if(!d8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":d8(this.o).rb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Wl(c[0],c[1]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.rx(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();N8(this,0==c?void 0:c);break;case "control_seek":N8(this,c[0]);break;case "control_subtitles_set_track":M8(this,c[0]);break;case "control_set_audio_track":c=c[0],L8(this)&&this.o.rx(this.A.getVideoData(1).videoId,c)}};
g.h.PR=function(a){this.L.VK(a)};
g.h.rX=function(a){this.FC("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.RF=function(){var a=this.A.Bc("captions","track");g.Yb(a)||M8(this,a)};
g.h.WD=function(a){if(L8(this)){this.o.unsubscribe("remotePlayerChange",this.cn,this);var b=Math.round(a.volume);a=!!a.muted;var c=d8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.cn,this)}};
g.h.lT=function(){g.Yb(this.G)||mGa(this,this.G);this.H=!1};
g.h.kE=function(a,b){this.F.stop();2==b&&this.OF()};
g.h.cn=function(){if(L8(this)){this.C.stop();var a=d8(this.o);switch(a.o){case 1080:case 1081:case 1084:case 1085:this.D.G=1;break;case 1082:case 1083:this.D.G=0;break;default:this.D.G=-1}switch(a.o){case 1081:case 1:K8(this,new g.FP(8));this.NF();break;case 1085:case 3:K8(this,new g.FP(9));break;case 1083:case 0:K8(this,new g.FP(2));this.K.stop();J8(this,this.A.getVideoData().lengthSeconds);break;case 1084:K8(this,new g.FP(4));break;case 2:K8(this,new g.FP(4));J8(this,Z7(a));break;case -1:K8(this,
new g.FP(64));break;case -1E3:K8(this,new g.FP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=d8(this.o).A;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,mGa(this,a));a=d8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.sG()}else lGa(this)};
g.h.hE=function(){this.A.V("mdxpreviousnextchange")};
g.h.nq=function(){L8(this)||lGa(this)};
g.h.aK=function(){this.o.Hz()};
g.h.ID=function(a){a&&(a=g.IE("/watch_queue_ajax",{method:"GET",cd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.AV,this)}))&&(this.O=(0,g.B)(a.abort,a))};
g.h.AV=function(a,b){var c=new g.YO(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.ZD=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.HD=function(){this.A.V("mdxautoplaycanceled")};
g.h.TP=function(a,b){-1==d8(this.o).o?N8(this,a):b&&this.o.HG(a)};
g.h.sG=function(){if(L8(this)){var a=d8(this.o);this.B.Ia(this.U);a.muted?this.A.mute():this.A.jg();this.A.setVolume(a.volume);this.U=this.B.R(this.A,"onVolumeChange",this.WD)}};
g.h.NF=function(){this.C.stop();if(!this.o.ka()){var a=d8(this.o);a.rb()&&K8(this,new g.FP(8));J8(this,Z7(a));this.C.start()}};
g.h.OF=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.F.start()};g.t(O8,g.W);O8.prototype.D=function(a){oGa(this,a.state)};g.t(P8,g.wY);P8.prototype.L=function(){var a=this.B.Bc("remote","receivers");a&&1<a.length&&!this.B.Bc("remote","quickCast")?(this.J=g.gb(a,this.F,this),g.xY(this,(0,g.J)(a,this.F)),a=this.B.Bc("remote","currentReceiver"),this.Bf(this.F(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.F=function(a){return a.key};
P8.prototype.Af=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
P8.prototype.Dd=function(a){g.wY.prototype.Dd.call(this,a);this.B.Ud("remote","currentReceiver",this.J[a]);this.D.Rb()};g.t(Q8,g.yU);g.h=Q8.prototype;g.h.create=function(){fGa(g.cN(g.Y(this.player)));this.D.push(g.mG("yt-remote-before-disconnect",this.LR,this));this.D.push(g.mG("yt-remote-connection-change",this.FU,this));this.D.push(g.mG("yt-remote-receiver-availability-change",this.iE,this));this.D.push(g.mG("yt-remote-auto-connect",this.DU,this));this.D.push(g.mG("yt-remote-receiver-resumed",this.CU,this));this.iE()};
g.h.load=function(){this.player.Tu();g.yU.prototype.load.call(this);this.C=new I8(this,this.player,this.o);var a=(a=kGa())?a.currentTime:0;var b=G8()?new c8(B8(),void 0):null;0==a&&b&&(a=Z7(d8(b)));0!=a&&(this.J=a||0,this.player.V("progresssync",a,void 0));nGa(this,this.F,this.F);g.L_(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.mf(this.C,this.o);this.o=this.C=null;g.yU.prototype.unload.call(this);g.L_(this.player.app,5)};
g.h.X=function(){g.nG(this.D);g.yU.prototype.X.call(this)};
g.h.Qm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.FC.apply(this.C,[a].concat(g.ea(c)))};
g.h.QK=function(){return this.loaded?this.C.suggestion:null};
g.h.ag=function(){return this.o?d8(this.o).ag:!1};
g.h.hasNext=function(){return this.o?d8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.HP=function(){var a=d8(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Vc():!a.isAdPlaying()&&this.player.Vc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+X7(a):a.C,isPeggedToLive:1>=(a.F?a.B+X7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+X7(a):a.B,seekableStart:0<a.D?a.D+X7(a):a.D}};
g.h.IP=function(){this.o&&this.o.FG()};
g.h.JP=function(){this.o&&this.o.GG()};
g.h.LR=function(a){1==a&&(this.K=this.o?d8(this.o):null)};
g.h.FU=function(){var a=G8()?new c8(B8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.lf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.kC(a.videoId,Z7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.iE=function(){this.H=[this.A].concat(hGa());var a=C8()||this.A;R8(this,a);this.player.ya("onMdxReceiversChange")};
g.h.DU=function(){var a=C8();R8(this,a)};
g.h.CU=function(){this.B=C8()};
g.h.GP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?T7():R8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&T7(),!0):!1}};
g.h.KP=function(){h8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Dc=function(){return!1};g.xX.remote=Q8;})(_yt_player);
